#!/bin/bash
set -x

branchName=$1
repository=$2
platform=$3
currentVersion=$4
newVersion=$5

export JAVA_HOME=$6

echo "JAVA: ${JAVA_HOME}"
if [[ "$branchName" =~ renovate/quarkus ]]; then
  /tmp/renovate/repos/$platform/$repository/mvnw versions:set-property -Dproperty=quarkus-maven-plugin -DnewVersion=$currentVersion -f /tmp/renovate/repos/$platform/$repository/pom.xml
  /tmp/renovate/repos/$platform/$repository/mvnw -f /tmp/renovate/repos/$platform/$repository/pom.xml io.quarkus.platform:quarkus-maven-plugin:$newVersion:update
fi