#!/bin/bash
set -x

branchName=$1
repository=$2
platform=$3
currentVersion=$4
newVersion=$5


if [[ "$branchName" =~ renovate/quarkus ]]; then
  mavenVersion = `./mvnw -v`
  echo "MAVEN VERSION: ${mavenVersion}"
  /tmp/renovate/repos/$platform/$repository/mvnw versions:set-property -Dproperty=quarkus-maven-plugin -DnewVersion=$currentVersion -f /tmp/renovate/repos/$platform/$repository/pom.xml
  /tmp/renovate/repos/$platform/$repository/mvnw -f /tmp/renovate/repos/$platform/$repository/pom.xml io.quarkus.platform:quarkus-maven-plugin:$newVersion:update
fi